# Generated by Django 3.2.7 on 2021-09-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimage',
            field=models.ImageField(blank=True, default='image/default/blog-1.jpg', upload_to='image/'),
        ),
    ]
